language: node_js
node_js:
  - 4
  - stable
before_install:
  - if [[ $(npm --version) == 1* ]]; then npm install -g npm@latest-2; fi
after_success:
  - if [[ $(node --version) == v4* ]]; then npm run test:coverage; fi
